### ISSUE TITLE
Implement alphanum when sorting cards by number

### ISSUE THREAD

**Issue by lsmoura** [mtgjson/mtgjson4_temporary#19]
Reference: http://www.davekoelle.com/alphanum.html

**Comment by beingfrankly** [comment]
Hi @lsmoura, this issue looks interesting. I would like to claim it for Hacktoberfest.

**Comment by lsmoura** [comment]
@fvaneldijk Sweet! Go for it.
You need to fix the sorting on the `sets.js` file. It's inside the `set_save()` function. It currently sorts using `localeCompare()`, so it goes like this:

```
1
10
11
12
...
2
20
21
3
4
5
...
```

What we want is:

```
1
2
3
4
...
9
10
11
...
```

**Comment by manishrw** [comment]
Hey, I already worked on it. :-/
I apologise but I've sent the pull request.

**Comment by yrahul3910** [comment]
Is this still open?

**Comment by ZeldaZach** [comment]
I believe @manishrw started working on this already, but we have a few other tickets if you guys would like to check them out! @yrahul3910 @fvaneldijk 

(In the future, can you just claim the ticket first @manishrw ? Thanks!)

**Comment by manishrw** [comment]
sure mate :+1:

**Comment by lsmoura** [comment]
Fixed by 44d52d7bea8cc9a47409a116e2a9e79843dffa69
