### ISSUE TITLE
Implement reserved

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson4_temporary#41]
If on reserved list = true

**Comment by lsmoura** [comment]
List of cards: http://magic.wizards.com/en/articles/archive/official-reprint-policy-2010-03-10

**Comment by ZeldaZach** [comment]
Will be implemented w/ "Fixes_XXX" (https://github.com/mtgjson/mtgjson/blob/master/shared/C.js#L4750)
