### ISSUE TITLE
Nemesis Set Code

### ISSUE THREAD

**Issue by dev-id** [mtgjson/mtgjson4_temporary#52]
The set code for Nemesis should be NEM

http://magic.wizards.com/en/articles/archive/ask-wizards-august-2004-2004-08-02

**Comment by tooomm** [comment]
There might be others too.

Cross referencing interesting comments:
https://github.com/mtgjson/mtgjson/issues/182#issuecomment-227214984
https://github.com/mtgjson/mtgjson/issues/156#issuecomment-215835896

CC: @fenhl

**Comment by fenhl** [comment]
I believe the set codes should be:
- NEM for _Nemesis_
- P02 for _Portal Second Age_
- CM1 for _Commander's Arsenal_
- DDL for _Duel Decks: Heroes vs. Monsters_

For NEM and P02, the Ask Wizards article clearly lists these set codes and there are to my knowledge no official sources contradicting them.

For CM1 and DDL, those are the the set codes used by Gatherer, and the Card Set Archive is known to be incorrect in other instances (e.g. listing _Theros_ as THR, which is contradicted by every other official source, including Gatherer, the set announcement post, and [an answer by Matt Tabak](http://tabakrules.tumblr.com/post/144445611844/whats-the-official-set-code-for-theros-the-card)). Additionally, CM1 makes more sense as it does not contradict the announced set code of CMA for _Commander Anthology_, and DDL is more consistent with the other Duel Decks.

**Comment by tooomm** [comment]
If `Nemesis` gets finally corrected, we have to update the documentation on the page as well, since the example there is Nemesis: http://mtgjson.com/documentation.html

**Comment by ZeldaZach** [comment]
Addressed the 4 set code corrections

**Comment by tooomm** [comment]
Maybe leave still open to not forget to adjust the docs later.
(I assume it's only addressed in the v4 rewrite for now)
>If Nemesis gets finally corrected, we have to update the documentation on the page as well, since the example there is Nemesis: http://mtgjson.com/documentation.html
