### ISSUE TITLE
Feature request: Incorporate version

### ISSUE THREAD

**Issue by mildmongrel** [mtgjson/mtgjson4_temporary#53]
Can the version number of the file(s) be included in a top-level node?

i.e.

{ version : "4.0.0" }

**Comment by fenhl** [comment]
@tooomm has additionally requested a date of creation field in mtgjson/mtgjson#347.

**Comment by ZeldaZach** [comment]
Addressed in https://github.com/mtgjson/mtgjson-python/commit/d4046c035bf48e1f8613e3c9ced527af8922fcd0

**Comment by tooomm** [comment]
Any reason you don't want to add a date field too, to easily check when last updates happened or changes got applied?

**Comment by ZeldaZach** [comment]
Didn't see that part; decent idea
