### ISSUE TITLE
Color identity formatting is inconsistent with color

### ISSUE THREAD

**Issue by fenhl** [mtgjson/mtgjson4_temporary#56]
See mtgjson/mtgjson#358.

> The "colorIdentity" array uses single letter abbreviations ("W", "U", etc), while the "colors" array uses full words.

We should probably just use full words for both.

**Comment by taw** [comment]
It's slightly easier to work with single color abbreviations than words, but should be same one way or the other.

**Comment by KingSupernova31** [comment]
Yeah, there's no reason they should be inconsistent. It just requires extra work when doing any sort of comparison or sorting.

**Comment by ZeldaZach** [comment]
It now will work in WUBRG order, for the time being.

**Comment by tooomm** [comment]
So both, `"colorIdentity"` and `"colors"`, use single letter abbreviations now?

**Comment by ZeldaZach** [comment]
That is correct
